# Exerc√≠cios com pandas

In [ ]:
import pandas as pd

# 1. Abra o dataset "iris.csv" como um dataframe do pandas

Lembrar de fazer upload do arquivo para o caderno antes de tentar carregar o arquivo como dataframe!

In [ ]:
iris_df = pd.read_csv("iris.csv")

# 2. Visualise as primeiras 5 linhas do dataframe

In [ ]:
# resposta 1
iris_df.head()

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
# resposta 2
iris_df.iloc[0:5,:]

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
# resposta 3
iris_df[0:5]

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
# resposta 4
iris_df[:5]

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

# 3. Imprima os nomes das colunas

In [ ]:
# resposta 1
iris_df.columns

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')

In [ ]:
# resposta 2
iris_df.dtypes

sepallength    float64
sepalwidth     float64
petallength    float64
petalwidth     float64
class           object
dtype: object

In [ ]:
# resposta 3
cols = list(iris_df.columns)
print(cols)

['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class']

In [ ]:
# resposta 4
iris_df[0:0]

Empty DataFrame
Columns: [sepallength, sepalwidth, petallength, petalwidth, class]
Index: []

# 4. Quantas colunas e quantas linhas tem o dataframe?

In [ ]:
# resposta 1
iris_df.shape

(150, 5)

In [ ]:
# resposta 2
rows = iris_df.shape[0]
cols = iris_df.shape[1]
print("n√∫mero de linhas:", rows)
print("n√∫mero de colunas:", cols)

n√∫mero de linhas: 150
n√∫mero de colunas: 5

In [ ]:
# resposta 3
n_colunas = len(iris_df.columns)
n_linhas = len(iris_df)

print("n√∫mero de colunas:", n_colunas)
print("n√∫mero de linhas:", n_linhas)

n√∫mero de colunas: 5
n√∫mero de linhas: 150

In [ ]:
# resposta 4
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sepallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwidth   150 non-null    float64
 4   class        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# 5. Fa√ßa um subset do dataframe contendo apenas as linhas de n√∫mero 10 a 20. Salve esse subset em um novo dataframe

In [ ]:
# resposta 1
iris_sliced = iris_df[9:20]
iris_sliced

    sepallength  sepalwidth  petallength  petalwidth        class
9           4.9         3.1          1.5         0.1  Iris-setosa
10          5.4         3.7          1.5         0.2  Iris-setosa
11          4.8         3.4          1.6         0.2  Iris-setosa
12          4.8         3.0          1.4         0.1  Iris-setosa
13          4.3         3.0          1.1         0.1  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
15          5.7         4.4          1.5         0.4  Iris-setosa
16          5.4         3.9          1.3         0.4  Iris-setosa
17          5.1         3.5          1.4         0.3  Iris-setosa
18          5.7         3.8          1.7         0.3  Iris-setosa
19          5.1         3.8          1.5         0.3  Iris-setosa

In [ ]:
# resposta 2
iris_sliced = iris_df.iloc[9:20,:]
iris_sliced

    sepallength  sepalwidth  petallength  petalwidth        class
9           4.9         3.1          1.5         0.1  Iris-setosa
10          5.4         3.7          1.5         0.2  Iris-setosa
11          4.8         3.4          1.6         0.2  Iris-setosa
12          4.8         3.0          1.4         0.1  Iris-setosa
13          4.3         3.0          1.1         0.1  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
15          5.7         4.4          1.5         0.4  Iris-setosa
16          5.4         3.9          1.3         0.4  Iris-setosa
17          5.1         3.5          1.4         0.3  Iris-setosa
18          5.7         3.8          1.7         0.3  Iris-setosa
19          5.1         3.8          1.5         0.3  Iris-setosa

Lembre-se que Python come√ßa a contar a partir do zero. Para facilitar as opera√ß√µes, podemos tamb√©m modificar o index para que ele comece do 1:

In [ ]:
# criar uma lista vazia
novo_index = []

# fazer um loop em uma lista de n√∫meros de tamanho igual ao n√∫mero de linhas (150)
for numero in range(150):
  novo_index.append(numero + 1)   # acrescentamos +1 para que o index comece do 1

# atribuir os valores da nova lista como index do dataframe
iris_df.index = novo_index

In [ ]:
iris_df.head()

   sepallength  sepalwidth  petallength  petalwidth        class
1          5.1         3.5          1.4         0.2  Iris-setosa
2          4.9         3.0          1.4         0.2  Iris-setosa
3          4.7         3.2          1.3         0.2  Iris-setosa
4          4.6         3.1          1.5         0.2  Iris-setosa
5          5.0         3.6          1.4         0.2  Iris-setosa

# 6. Crie um novo dataset contendo apenas as colunas "sepallength" e "class"

In [ ]:
# resposta 1
iris_specific_columns = iris_df[["sepallength","class"]]
iris_specific_columns

     sepallength           class
0            5.1     Iris-setosa
1            4.9     Iris-setosa
2            4.7     Iris-setosa
3            4.6     Iris-setosa
4            5.0     Iris-setosa
..           ...             ...
145          6.7  Iris-virginica
146          6.3  Iris-virginica
147          6.5  Iris-virginica
148          6.2  Iris-virginica
149          5.9  Iris-virginica

[150 rows x 2 columns]

# 7. Imprima apenas os valores da linha 4

In [ ]:
# resposta 1
## lembrando que agora renomeamos o index, ent√£o a linha 4 √© o index 4
iris_df.iloc[4]

sepallength            5.0
sepalwidth             3.6
petallength            1.4
petalwidth             0.2
class          Iris-setosa
Name: 5, dtype: object

In [ ]:
# resposta 2
iris_df.iloc[4:5]

   sepallength  sepalwidth  petallength  petalwidth        class
5          5.0         3.6          1.4         0.2  Iris-setosa

# 8. Filtre o dataframe para mostrar apenas valores de "Iris-setosa"

In [ ]:
iris_df.loc[iris_df["class"] == "Iris-setosa"]

    sepallength  sepalwidth  petallength  petalwidth        class
0           5.1         3.5          1.4         0.2  Iris-setosa
1           4.9         3.0          1.4         0.2  Iris-setosa
2           4.7         3.2          1.3         0.2  Iris-setosa
3           4.6         3.1          1.5         0.2  Iris-setosa
4           5.0         3.6          1.4         0.2  Iris-setosa
5           5.4         3.9          1.7         0.4  Iris-setosa
6           4.6         3.4          1.4         0.3  Iris-setosa
7           5.0         3.4          1.5         0.2  Iris-setosa
8           4.4         2.9          1.4         0.2  Iris-setosa
9           4.9         3.1          1.5         0.1  Iris-setosa
10          5.4         3.7          1.5         0.2  Iris-setosa
11          4.8         3.4          1.6         0.2  Iris-setosa
12          4.8         3.0          1.4         0.1  Iris-setosa
13          4.3         3.0          1.1         0.1  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
15          5.7         4.4          1.5         0.4  Iris-setosa
16          5.4         3.9          1.3         0.4  Iris-setosa
17          5.1         3.5          1.4         0.3  Iris-setosa
18          5.7         3.8          1.7         0.3  Iris-setosa
19          5.1         3.8          1.5         0.3  Iris-setosa
20          5.4         3.4          1.7         0.2  Iris-setosa
21          5.1         3.7          1.5         0.4  Iris-setosa
22          4.6         3.6          1.0         0.2  Iris-setosa
23          5.1         3.3          1.7         0.5  Iris-setosa
24          4.8         3.4          1.9         0.2  Iris-setosa
25          5.0         3.0          1.6         0.2  Iris-setosa
26          5.0         3.4          1.6         0.4  Iris-setosa
27          5.2         3.5          1.5         0.2  Iris-setosa
28          5.2         3.4          1.4         0.2  Iris-setosa
29          4.7         3.2          1.6         0.2  Iris-setosa
30          4.8         3.1          1.6         0.2  Iris-setosa
31          5.4         3.4          1.5         0.4  Iris-setosa
32          5.2         4.1          1.5         0.1  Iris-setosa
33          5.5         4.2          1.4         0.2  Iris-setosa
34          4.9         3.1          1.5         0.1  Iris-setosa
35          5.0         3.2          1.2         0.2  Iris-setosa
36          5.5         3.5          1.3         0.2  Iris-setosa
37          4.9         3.1          1.5         0.1  Iris-setosa
38          4.4         3.0          1.3         0.2  Iris-setosa
39          5.1         3.4          1.5         0.2  Iris-setosa
40          5.0         3.5          1.3         0.3  Iris-setosa
41          4.5         2.3          1.3         0.3  Iris-setosa
42          4.4         3.2          1.3         0.2  Iris-setosa
43          5.0         3.5          1.6         0.6  Iris-setosa
44          5.1         3.8          1.9         0.4  Iris-setosa
45          4.8         3.0          1.4         0.3  Iris-setosa
46          5.1         3.8          1.6         0.2  Iris-setosa
47          4.6         3.2          1.4         0.2  Iris-setosa
48          5.3         3.7          1.5         0.2  Iris-setosa
49          5.0         3.3          1.4         0.2  Iris-setosa

‚ùó Importante!

O `=` n√£o siginifica "igual"; √© uma atribui√ß√£o.

Para fazer compara√ß√µes, utilizamos o `==`

# 9. Qual a quantidade de valores/linhas de cada esp√©cie de Iris?

In [ ]:
# resposta 1
iris_df["class"].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: class, dtype: int64

In [ ]:
# resposta 2
n_valores_setosa = len(iris_df[iris_df["class"] == 'Iris-setosa'])
print("quantidade de valores de I. setosa:", n_valores_setosa)

n_valores_versicolor = len(iris_df[iris_df["class"] == 'Iris-versicolor'])
print("quantidade de valores de I. versicolor:", n_valores_versicolor)

n_valores_virginica = len(iris_df[iris_df["class"] == 'Iris-virginica'])
print("quantidade de valores de I. virginica:", n_valores_virginica)

quantidade de valores de I. setosa: 50
quantidade de valores de I. versicolor: 50
quantidade de valores de I. virginica: 50

# 10. Calcule, para cada coluna num√©rica:
 * a) a soma de valores
 * b) a m√©dia
 * c) a mediana

In [ ]:
# resposta 1
## sepal length
sepal_len_sum = iris_df["sepallength"].sum()
print("soma da coluna 'sepallength':", sepal_len_sum)
sepal_len_mean = iris_df["sepallength"].mean()
print("m√©dia da coluna 'sepallength':", sepal_len_mean)
sepal_len_median = iris_df["sepallength"].median()
print("mediana da coluna 'sepallength':", sepal_len_median)

print()

## sepal width
print("soma da coluna 'sepalwidth':", iris_df["sepalwidth"].sum())
print("m√©dia da coluna 'sepalwidth':", iris_df["sepalwidth"].mean())
print("mediana da coluna 'sepalwidth':", iris_df["sepalwidth"].median())

print()

## petal length
print("soma da coluna 'petallength':", iris_df["petallength"].sum())
print("m√©dia da coluna 'petallength':", iris_df["petallength"].mean())
print("mediana da coluna 'petallength':", iris_df["petallength"].median())

print()

## petal width
print("soma da coluna 'petalwidth':", iris_df["petalwidth"].sum())
print("m√©dia da coluna 'petalwidth':", iris_df["petalwidth"].mean())
print("mediana da coluna 'petalwidth':", iris_df["petalwidth"].median())

soma da coluna 'sepallength': 876.5
m√©dia da coluna 'sepallength': 5.843333333333334
mediana da coluna 'sepallength': 5.8

soma da coluna 'sepalwidth': 458.1
m√©dia da coluna 'sepalwidth': 3.0540000000000003
mediana da coluna 'sepalwidth': 3.0

soma da coluna 'petallength': 563.8
m√©dia da coluna 'petallength': 3.758666666666666
mediana da coluna 'petallength': 4.35

soma da coluna 'petalwidth': 179.8
m√©dia da coluna 'petalwidth': 1.1986666666666668
mediana da coluna 'petalwidth': 1.3

In [ ]:
# resposta 2
iris_df.agg(['sum', 'mean', 'median'])

,sepallength,sepalwidth,petallength,petalwidth,class
sum,876.500000,458.100,563.800000,179.800000,Iris-setosaIris-setosaIris-setosaIris-setosaIr...
mean,5.843333,3.054,3.758667,1.198667,NaN
median,5.800000,3.000,4.350000,1.300000,NaN

In [ ]:
# resposta 2
# mostrando apenas as colunas num√©ricas
iris_df.iloc[:,0:4].agg(['sum', 'mean', 'median'])

        sepallength  sepalwidth  petallength  petalwidth
sum      876.500000     458.100   563.800000  179.800000
mean       5.843333       3.054     3.758667    1.198667
median     5.800000       3.000     4.350000    1.300000

In [ ]:
# resposta 3
iris_df.describe()
## aqui faltam os valores de mediana e soma

       sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [ ]:
# resposta 4
## retirar coluna 'class' primeiro
iris_noclass = iris_df.iloc[:,0:-1]

media = iris_noclass.mean()
mediana = iris_noclass.median()
soma = iris_noclass.sum()
print(media)
print()
print(mediana)
print()
print(soma)

sepallength    5.843333
sepalwidth     3.054000
petallength    3.758667
petalwidth     1.198667
dtype: float64

sepallength    5.80
sepalwidth     3.00
petallength    4.35
petalwidth     1.30
dtype: float64

sepallength    876.5
sepalwidth     458.1
petallength    563.8
petalwidth     179.8
dtype: float64

# 11. Verifique quais os valores m√°ximo e m√≠nimo para cada coluna num√©rica

In [ ]:
# resposta 1
sepal_len_max = iris_df["sepallength"].max()
sepal_len_min = iris_df["sepallength"].min()
print("Valor m√°ximo para coluna 'sepallength':", sepal_len_max)
print("Valor m√≠nimo para coluna 'sepallength':", sepal_len_min)

print()

print("Valor m√°ximo para coluna 'sepalwidth':", iris_df["sepalwidth"].max())
print("Valor m√≠nimo para coluna 'sepalwidth':", iris_df["sepalwidth"].min())

print()

print("Valor m√°ximo para coluna 'petallength':", iris_df["petallength"].max())
print("Valor m√≠nimo para coluna 'petallength':", iris_df["petallength"].min())

print()

print("Valor m√°ximo para coluna 'petalwidth':", iris_df["petalwidth"].max())
print("Valor m√≠nimo para coluna 'petalwidth':", iris_df["petalwidth"].min())

Valor m√°ximo para coluna 'sepallength': 7.9
Valor m√≠nimo para coluna 'sepallength': 4.3

Valor m√°ximo para coluna 'sepalwidth': 4.4
Valor m√≠nimo para coluna 'sepalwidth': 2.0

Valor m√°ximo para coluna 'petallength': 6.9
Valor m√≠nimo para coluna 'petallength': 1.0

Valor m√°ximo para coluna 'petalwidth': 2.5
Valor m√≠nimo para coluna 'petalwidth': 0.1

In [ ]:
# resposta 2
iris_df.iloc[:,0:4].agg(['max', 'min'])

     sepallength  sepalwidth  petallength  petalwidth
max          7.9         4.4          6.9         2.5
min          4.3         2.0          1.0         0.1

In [ ]:
# resposta 3
iris_df.describe()

       sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

# 12. Crie uma nova coluna com a soma de valores das colunas num√©ricas

In [ ]:
iris_noclass = iris_df.iloc[:,0:-1]
iris_df['Soma'] = iris_noclass.sum(axis=1)
iris_df

     sepallength  sepalwidth  petallength  petalwidth           class  Soma
1            5.1         3.5          1.4         0.2     Iris-setosa  10.2
2            4.9         3.0          1.4         0.2     Iris-setosa   9.5
3            4.7         3.2          1.3         0.2     Iris-setosa   9.4
4            4.6         3.1          1.5         0.2     Iris-setosa   9.4
5            5.0         3.6          1.4         0.2     Iris-setosa  10.2
..           ...         ...          ...         ...             ...   ...
146          6.7         3.0          5.2         2.3  Iris-virginica  17.2
147          6.3         2.5          5.0         1.9  Iris-virginica  15.7
148          6.5         3.0          5.2         2.0  Iris-virginica  16.7
149          6.2         3.4          5.4         2.3  Iris-virginica  17.3
150          5.9         3.0          5.1         1.8  Iris-virginica  15.8

[150 rows x 6 columns]

# 13. Renomeie as colunas com os seguintes nomes:

| Nome antigo | Nome novo    |
|-------------|--------------|
| sepallength | Sepal length |
| sepalwidth  | Sepal width  |
| petallength | Petal length |
| petalwidth  | Petal width  |
| class       | Species      |

In [ ]:
# criar dicionario associando nomes antigos aos nomes novos
dicionario_novos_nomes = {'sepallength': 'Sepal length',
                          'sepalwidth': 'Sepal width',
                          'petallength': 'Petal length',
                          'petalwidth': 'Petal width',
                          'class': 'Species'}

# renomear as colunas utilizando o dicion√°rio acima
iris_renamed = iris_df.rename(columns=dicionario_novos_nomes)
iris_renamed.head()

   Sepal length  Sepal width  Petal length  Petal width      Species  Soma
0           5.1          3.5           1.4          0.2  Iris-setosa  10.2
1           4.9          3.0           1.4          0.2  Iris-setosa   9.5
2           4.7          3.2           1.3          0.2  Iris-setosa   9.4
3           4.6          3.1           1.5          0.2  Iris-setosa   9.4
4           5.0          3.6           1.4          0.2  Iris-setosa  10.2

# 14. Para cada vari√°vel (tamanhos e comprimentos de s√©palas e p√©talas), calcule a m√©dia e a mediana de cada esp√©cie

In [ ]:
# media
iris_df.groupby('class').mean()

## tamb√©m podemos retirar a coluna "soma" para ficar apenas com os dados relevantes

                 sepallength  sepalwidth  petallength  petalwidth    Soma
class
Iris-setosa            5.006       3.418        1.464       0.244  10.132
Iris-versicolor        5.936       2.770        4.260       1.326  14.292
Iris-virginica         6.588       2.974        5.552       2.026  17.140

In [ ]:
# mediana
iris_df.groupby('class').median()

                 sepallength  sepalwidth  petallength  petalwidth   Soma
class
Iris-setosa              5.0         3.4         1.50         0.2  10.20
Iris-versicolor          5.9         2.8         4.35         1.3  14.35
Iris-virginica           6.5         3.0         5.55         2.0  17.20

# 15. Verifique quantos valores em branco/faltantes est√£o presentes no dataframe

In [ ]:
iris_renamed.isnull().sum()

Sepal length    0
Sepal width     0
Petal length    0
Petal width     0
Species         0
Soma            0
dtype: int64

## 16. Crie uma coluna com a √°rea da p√©tala

OBS: considere que a p√©tala √© um ret√¢ngulo

In [ ]:
iris_df['petal_area'] = iris_df['petallength'] * iris_df['petalwidth']
iris_df

,sepallength,sepalwidth,petallength,petalwidth,class,Soma,petal_area
1,5.1,3.5,1.4,0.2,Iris-setosa,10.2,0.28
2,4.9,3.0,1.4,0.2,Iris-setosa,9.5,0.28
3,4.7,3.2,1.3,0.2,Iris-setosa,9.4,0.26
4,4.6,3.1,1.5,0.2,Iris-setosa,9.4,0.30
5,5.0,3.6,1.4,0.2,Iris-setosa,10.2,0.28
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,Iris-virginica,17.2,11.96
147,6.3,2.5,5.0,1.9,Iris-virginica,15.7,9.50
148,6.5,3.0,5.2,2.0,Iris-virginica,16.7,10.40
149,6.2,3.4,5.4,2.3,Iris-virginica,17.3,12.42
150,5.9,3.0,5.1,1.8,Iris-virginica,15.8,9.18

## 17. Filtre o dataframe para √°reas de p√©tala com valor entre 7 e 9, e ordene os valores de maior para menor

In [ ]:
# primeiro filtro (valor > 7)
filtro_maior_7 = iris_df[iris_df['petal_area'] > 7]
filtro_maior_7

,sepallength,sepalwidth,petallength,petalwidth,class,Soma,petal_area
53,6.9,3.1,4.9,1.5,Iris-versicolor,16.4,7.35
57,6.3,3.3,4.7,1.6,Iris-versicolor,15.9,7.52
71,5.9,3.2,4.8,1.8,Iris-versicolor,15.7,8.64
73,6.3,2.5,4.9,1.5,Iris-versicolor,15.2,7.35
78,6.7,3.0,5.0,1.7,Iris-versicolor,16.4,8.50
84,6.0,2.7,5.1,1.6,Iris-versicolor,15.4,8.16
86,6.0,3.4,4.5,1.6,Iris-versicolor,15.5,7.20
87,6.7,3.1,4.7,1.5,Iris-versicolor,16.0,7.05
101,6.3,3.3,6.0,2.5,Iris-virginica,18.1,15.00
102,5.8,2.7,5.1,1.9,Iris-virginica,15.5,9.69
103,7.1,3.0,5.9,2.1,Iris-virginica,18.1,12.39
104,6.3,2.9,5.6,1.8,Iris-virginica,16.6,10.08
105,6.5,3.0,5.8,2.2,Iris-virginica,17.5,12.76
106,7.6,3.0,6.6,2.1,Iris-virginica,19.3,13.86
107,4.9,2.5,4.5,1.7,Iris-virginica,13.6,7.65
108,7.3,2.9,6.3,1.8,Iris-virginica,18.3,11.34
109,6.7,2.5,5.8,1.8,Iris-virginica,16.8,10.44
110,7.2,3.6,6.1,2.5,Iris-virginica,19.4,15.25
111,6.5,3.2,5.1,2.0,Iris-virginica,16.8,10.20
112,6.4,2.7,5.3,1.9,Iris-virginica,16.3,10.07
113,6.8,3.0,5.5,2.1,Iris-virginica,17.4,11.55
114,5.7,2.5,5.0,2.0,Iris-virginica,15.2,10.00
115,5.8,2.8,5.1,2.4,Iris-virginica,16.1,12.24
116,6.4,3.2,5.3,2.3,Iris-virginica,17.2,12.19
117,6.5,3.0,5.5,1.8,Iris-virginica,16.8,9.90
118,7.7,3.8,6.7,2.2,Iris-virginica,20.4,14.74
119,7.7,2.6,6.9,2.3,Iris-virginica,19.5,15.87
120,6.0,2.2,5.0,1.5,Iris-virginica,14.7,7.50
121,6.9,3.2,5.7,2.3,Iris-virginica,18.1,13.11
122,5.6,2.8,4.9,2.0,Iris-virginica,15.3,9.80
123,7.7,2.8,6.7,2.0,Iris-virginica,19.2,13.40
124,6.3,2.7,4.9,1.8,Iris-virginica,15.7,8.82
125,6.7,3.3,5.7,2.1,Iris-virginica,17.8,11.97
126,7.2,3.2,6.0,1.8,Iris-virginica,18.2,10.80
127,6.2,2.8,4.8,1.8,Iris-virginica,15.6,8.64
128,6.1,3.0,4.9,1.8,Iris-virginica,15.8,8.82
129,6.4,2.8,5.6,2.1,Iris-virginica,16.9,11.76
130,7.2,3.0,5.8,1.6,Iris-virginica,17.6,9.28
131,7.4,2.8,6.1,1.9,Iris-virginica,18.2,11.59
132,7.9,3.8,6.4,2.0,Iris-virginica,20.1,12.80
133,6.4,2.8,5.6,2.2,Iris-virginica,17.0,12.32
134,6.3,2.8,5.1,1.5,Iris-virginica,15.7,7.65
135,6.1,2.6,5.6,1.4,Iris-virginica,15.7,7.84
136,7.7,3.0,6.1,2.3,Iris-virginica,19.1,14.03
137,6.3,3.4,5.6,2.4,Iris-virginica,17.7,13.44
138,6.4,3.1,5.5,1.8,Iris-virginica,16.8,9.90
139,6.0,3.0,4.8,1.8,Iris-virginica,15.6,8.64
140,6.9,3.1,5.4,2.1,Iris-virginica,17.5,11.34
141,6.7,3.1,5.6,2.4,Iris-virginica,17.8,13.44
142,6.9,3.1,5.1,2.3,Iris-virginica,17.4,11.73
143,5.8,2.7,5.1,1.9,Iris-virginica,15.5,9.69
144,6.8,3.2,5.9,2.3,Iris-virginica,18.2,13.57
145,6.7,3.3,5.7,2.5,Iris-virginica,18.2,14.25
146,6.7,3.0,5.2,2.3,Iris-virginica,17.2,11.96
147,6.3,2.5,5.0,1.9,Iris-virginica,15.7,9.50
148,6.5,3.0,5.2,2.0,Iris-virginica,16.7,10.40
149,6.2,3.4,5.4,2.3,Iris-virginica,17.3,12.42
150,5.9,3.0,5.1,1.8,Iris-virginica,15.8,9.18

In [ ]:
# segundo filtro (valor < 9)
filtro_menor_9 = filtro_maior_7[filtro_maior_7['petal_area'] < 9]
filtro_menor_9

,sepallength,sepalwidth,petallength,petalwidth,class,Soma,petal_area
53,6.9,3.1,4.9,1.5,Iris-versicolor,16.4,7.35
57,6.3,3.3,4.7,1.6,Iris-versicolor,15.9,7.52
71,5.9,3.2,4.8,1.8,Iris-versicolor,15.7,8.64
73,6.3,2.5,4.9,1.5,Iris-versicolor,15.2,7.35
78,6.7,3.0,5.0,1.7,Iris-versicolor,16.4,8.50
84,6.0,2.7,5.1,1.6,Iris-versicolor,15.4,8.16
86,6.0,3.4,4.5,1.6,Iris-versicolor,15.5,7.20
87,6.7,3.1,4.7,1.5,Iris-versicolor,16.0,7.05
107,4.9,2.5,4.5,1.7,Iris-virginica,13.6,7.65
120,6.0,2.2,5.0,1.5,Iris-virginica,14.7,7.50
124,6.3,2.7,4.9,1.8,Iris-virginica,15.7,8.82
127,6.2,2.8,4.8,1.8,Iris-virginica,15.6,8.64
128,6.1,3.0,4.9,1.8,Iris-virginica,15.8,8.82
134,6.3,2.8,5.1,1.5,Iris-virginica,15.7,7.65
135,6.1,2.6,5.6,1.4,Iris-virginica,15.7,7.84
139,6.0,3.0,4.8,1.8,Iris-virginica,15.6,8.64

In [ ]:
# ordenar do maior para o menor
# o df filtro_menor_9 cont√©m os dois filtros
df_final = filtro_menor_9.sort_values('petal_area', ascending=False)
df_final

,sepallength,sepalwidth,petallength,petalwidth,class,Soma,petal_area
124,6.3,2.7,4.9,1.8,Iris-virginica,15.7,8.82
128,6.1,3.0,4.9,1.8,Iris-virginica,15.8,8.82
71,5.9,3.2,4.8,1.8,Iris-versicolor,15.7,8.64
127,6.2,2.8,4.8,1.8,Iris-virginica,15.6,8.64
139,6.0,3.0,4.8,1.8,Iris-virginica,15.6,8.64
78,6.7,3.0,5.0,1.7,Iris-versicolor,16.4,8.50
84,6.0,2.7,5.1,1.6,Iris-versicolor,15.4,8.16
135,6.1,2.6,5.6,1.4,Iris-virginica,15.7,7.84
107,4.9,2.5,4.5,1.7,Iris-virginica,13.6,7.65
134,6.3,2.8,5.1,1.5,Iris-virginica,15.7,7.65
57,6.3,3.3,4.7,1.6,Iris-versicolor,15.9,7.52
120,6.0,2.2,5.0,1.5,Iris-virginica,14.7,7.50
53,6.9,3.1,4.9,1.5,Iris-versicolor,16.4,7.35
73,6.3,2.5,4.9,1.5,Iris-versicolor,15.2,7.35
86,6.0,3.4,4.5,1.6,Iris-versicolor,15.5,7.20
87,6.7,3.1,4.7,1.5,Iris-versicolor,16.0,7.05

In [ ]:
# mesma resposta acima, mas utilizando apenas um comando (fun√ß√µes encadeadas)
iris_df[(iris_df['petal_area'] > 7) & (iris_df['petal_area'] < 9)].sort_values('petal_area', ascending=False)

,sepallength,sepalwidth,petallength,petalwidth,class,Soma,petal_area
124,6.3,2.7,4.9,1.8,Iris-virginica,15.7,8.82
128,6.1,3.0,4.9,1.8,Iris-virginica,15.8,8.82
71,5.9,3.2,4.8,1.8,Iris-versicolor,15.7,8.64
127,6.2,2.8,4.8,1.8,Iris-virginica,15.6,8.64
139,6.0,3.0,4.8,1.8,Iris-virginica,15.6,8.64
78,6.7,3.0,5.0,1.7,Iris-versicolor,16.4,8.50
84,6.0,2.7,5.1,1.6,Iris-versicolor,15.4,8.16
135,6.1,2.6,5.6,1.4,Iris-virginica,15.7,7.84
107,4.9,2.5,4.5,1.7,Iris-virginica,13.6,7.65
134,6.3,2.8,5.1,1.5,Iris-virginica,15.7,7.65
57,6.3,3.3,4.7,1.6,Iris-versicolor,15.9,7.52
120,6.0,2.2,5.0,1.5,Iris-virginica,14.7,7.50
53,6.9,3.1,4.9,1.5,Iris-versicolor,16.4,7.35
73,6.3,2.5,4.9,1.5,Iris-versicolor,15.2,7.35
86,6.0,3.4,4.5,1.6,Iris-versicolor,15.5,7.20
87,6.7,3.1,4.7,1.5,Iris-versicolor,16.0,7.05